// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuxWindowService owns setup / profile / recovery webview windows that
 * Electron previously opened as BrowserWindow HTML UIs under src/native-ui/.
 * These Wails windows are hybrid stand-ins: they talk to Go via bindings and
 * cover shell startup flows while Cordis Host still owns full profile CRUD.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as url$0 from "../../../../../net/url/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseInfoDialog closes the Info status window.
 */
export function CloseInfoDialog(): $CancellablePromise<void> {
    return $Call.ByID(1877340953);
}

/**
 * CompleteProfileCreate records a create-profile outcome.
 * action: cancel | create; profile is the new name when creating.
 */
export function CompleteProfileCreate(action: string, profile: string): $CancellablePromise<void> {
    return $Call.ByID(4141344553, action, profile);
}

/**
 * CompleteProfileSelection records a profile-selector outcome.
 * action: cancel | create | restart | switch; profile is required for switch.
 */
export function CompleteProfileSelection(action: string, profile: string): $CancellablePromise<void> {
    return $Call.ByID(899512961, action, profile);
}

/**
 * CompleteRecovery records a recovery outcome.
 * Supported hybrid actions: restart | safe-mode | quit | profiles | control.
 * Checkpoint / plugin-uninstall / diagnostics / config actions return a clear
 * Host-controller debt dialog (see docs/wails-migration.md Recovery section).
 */
export function CompleteRecovery(action: string): $CancellablePromise<void> {
    return $Call.ByID(3261780963, action);
}

/**
 * CompleteSetup records a setup-wizard outcome and closes the wizard.
 * action is one of: continue, quit.
 */
export function CompleteSetup(action: string): $CancellablePromise<void> {
    return $Call.ByID(3573885833, action);
}

/**
 * LastResult returns the most recent auxiliary-window outcome.
 */
export function LastResult(): $CancellablePromise<$models.AuxWindowResult> {
    return $Call.ByID(1623415942);
}

/**
 * ListKnownProfiles returns profile names discovered from the default DSH home,
 * or a placeholder list when none are found (Host still owns authoritative CRUD).
 */
export function ListKnownProfiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1325114200);
}

/**
 * OpenInfoDialog opens a small webview Info dialog with title/message.
 * Used on Linux hybrid beds where GTK MessageDialog can be silent from menus.
 */
export function OpenInfoDialog(title: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(73972947, title, message);
}

/**
 * OpenProfileCreate opens the create-profile window.
 */
export function OpenProfileCreate(): $CancellablePromise<void> {
    return $Call.ByID(3888073656);
}

/**
 * OpenProfileSelector opens the profile selection window.
 */
export function OpenProfileSelector(): $CancellablePromise<void> {
    return $Call.ByID(71149513);
}

/**
 * OpenRecovery opens the startup recovery assistant.
 * detail is a short failure message shown in the UI.
 */
export function OpenRecovery(detail: string): $CancellablePromise<void> {
    return $Call.ByID(817924808, detail);
}

/**
 * OpenSetupWizard opens (or focuses) the setup wizard window.
 * Prefers Vite-built React native-ui when present under frontend/dist/shell-ui.
 */
export function OpenSetupWizard(): $CancellablePromise<void> {
    return $Call.ByID(2781172827);
}

/**
 * RecoveryDetail returns the failure text for the recovery window.
 */
export function RecoveryDetail(): $CancellablePromise<string> {
    return $Call.ByID(80258133);
}

/**
 * ReportRecoveryDebt surfaces precise Host API gaps for Recovery checkpoint/uninstall.
 */
export function ReportRecoveryDebt(kind: string): $CancellablePromise<void> {
    return $Call.ByID(2747606995, kind);
}

/**
 * ResolveAuxURLForTest exposes resolveAuxURL for unit tests.
 */
export function ResolveAuxURLForTest(name: string, query: url$0.Values): $CancellablePromise<string> {
    return $Call.ByID(3592518973, name, query);
}
