// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BridgeService replaces Electron preload/contextBridge + session auth for the
 * hybrid Wails shell. Host UI still loads via authenticated loopback URL;
 * renderer request-header injection is not available on Linux webkitgtk in
 * Wails v3 beta, so sidecar mode enables ordinary-browser Host access and this
 * service exposes native bindings the control UI / future Host bridge can call.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

/**
 * AuthenticateHostSession performs the Electron session.fetch equivalent:
 * GET authenticationUrl with the renderer access header, accepting Set-Cookie.
 * On success, navigates the main window to uiURL (usually the authenticated UI).
 * Note: webview cookie import from the Go jar is not available on all platforms;
 * the hybrid path therefore also relies on Host ordinary-browser access + loading
 * the authenticated URL directly in the webview.
 */
export function AuthenticateHostSession(authenticationURL: string, uiURL: string): $CancellablePromise<string> {
    return $Call.ByID(3927604233, authenticationURL, uiURL);
}

/**
 * BridgeStatus reports auth-bridge readiness for the control UI.
 */
export function BridgeStatus(): $CancellablePromise<string> {
    return $Call.ByID(1659680535);
}

/**
 * DesktopFilePathBridgeKey returns the preload main-world key for Host compatibility docs.
 */
export function DesktopFilePathBridgeKey(): $CancellablePromise<string> {
    return $Call.ByID(2385249847);
}

/**
 * GetPathForFile is the preload bridge stand-in. Electron used webUtils.getPathForFile;
 * Wails/webkitgtk does not expose OS paths for drag File objects on this box, so
 * callers receive a clear error instead of a fake path.
 */
export function GetPathForFile($0: string): $CancellablePromise<string> {
    return $Call.ByID(622438864, $0);
}

/**
 * HasRendererAccessHeader reports whether a token is configured (not the value).
 */
export function HasRendererAccessHeader(): $CancellablePromise<boolean> {
    return $Call.ByID(3480595264);
}

/**
 * IngestHostAuthHeaderLine parses "DSH_HOST_AUTH_HEADER <name> <value>" from Host stdout.
 */
export function IngestHostAuthHeaderLine(line: string): $CancellablePromise<boolean> {
    return $Call.ByID(3823066479, line);
}

/**
 * LoadAuthMetaFile reads optional JSON/plain meta written beside DSH_HOST_URL_FILE.
 * Supported plain format:
 * 
 * 	url=http://127.0.0.1:PORT/...
 * 	header=x-dsh-desktop-renderer TOKEN
 */
export function LoadAuthMetaFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(535483281, path);
}

/**
 * OpenExternal opens a URL with the OS default handler (replaces shell.openExternal).
 */
export function OpenExternal(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(2708623591, rawURL);
}

/**
 * RendererAccessHeaderName returns the configured header name, if any.
 */
export function RendererAccessHeaderName(): $CancellablePromise<string> {
    return $Call.ByID(1642851403);
}

/**
 * SetRendererAccessHeader stores the Host generation's renderer capability.
 * name should be x-dsh-desktop-renderer; value is the ephemeral token.
 */
export function SetRendererAccessHeader(name: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(580823976, name, value);
}
