// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CapabilitiesService ports Electron DesktopRuntime system surfaces that are
 * still feasible in the hybrid Wails shell: notifications, save/export dialogs,
 * reveal-in-folder, terminal launch, and a lightweight update check stub.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates performs a lightweight local probe (not electron-updater).
 * Full download/install remains Electron / future wails3 updater packaging debt.
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateCheckResult> {
    return $Call.ByID(3300687414);
}

/**
 * ExportTextFile writes contents to a path chosen via the save dialog.
 */
export function ExportTextFile(defaultFilename: string, contents: string): $CancellablePromise<string> {
    return $Call.ByID(2662728876, defaultFilename, contents);
}

/**
 * LanHttpsStatus reports that LAN HTTPS remains Host/Electron-owned for now.
 */
export function LanHttpsStatus(): $CancellablePromise<string> {
    return $Call.ByID(3796462409);
}

/**
 * LastUpdateCheck returns the most recent CheckForUpdates result.
 */
export function LastUpdateCheck(): $CancellablePromise<$models.UpdateCheckResult> {
    return $Call.ByID(3167788050);
}

/**
 * NotifyAttention shows a native notification (Electron notifyAttention stand-in).
 */
export function NotifyAttention(title: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(658386396, title, body);
}

/**
 * OpenTerminal launches a system terminal in a useful working directory.
 * Packaged DSH terminal shims remain Electron/macOS/Windows-owned; this is the
 * hybrid fallback (xdg-terminal-exec / Terminal.app / wt.exe / cmd).
 */
export function OpenTerminal(workdir: string): $CancellablePromise<void> {
    return $Call.ByID(3461547347, workdir);
}

/**
 * RevealInFileManager opens the OS file manager at path (selectFile when possible).
 */
export function RevealInFileManager(path: string, selectFile: boolean): $CancellablePromise<void> {
    return $Call.ByID(434138598, path, selectFile);
}

/**
 * SaveFileDialog opens a native save dialog and returns the chosen path.
 */
export function SaveFileDialog(defaultFilename: string): $CancellablePromise<string> {
    return $Call.ByID(2555592040, defaultFilename);
}
