// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuxWindowResult is the last settled action from an auxiliary window.
 */
export interface AuxWindowResult {
    "kind": string;
    "action": string;
    "profile"?: string;
    "detail"?: string;
}

/**
 * PlatformIdentityStatus documents what the hybrid shell owns vs Electron-only.
 */
export interface PlatformIdentityStatus {
    "appId": string;
    "appUserModelId": string;
    "dock": string;
    "crashReporter": string;
    "packagedUpdates": string;
    "applied": string;
}

/**
 * UpdateCheckResult is the hybrid update probe / download result.
 */
export interface UpdateCheckResult {
    "checkedAt": string;
    "currentHint": string;
    "latestHint": string;
    "status": string;
    "detail": string;
    "downloadPath"?: string;
    "canDownload": boolean;
    "releaseChannel": string;
}
