// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuxWindowResult is the last settled action from an auxiliary window.
 */
export interface AuxWindowResult {
    "kind": string;
    "action": string;
    "profile"?: string;
    "detail"?: string;
}

/**
 * UpdateCheckResult is a lightweight update probe result (not a full installer).
 */
export interface UpdateCheckResult {
    "checkedAt": string;
    "currentHint": string;
    "status": string;
    "detail": string;
}
