// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ShellService exposes native shell controls to the embedded control UI and to
 * future Cordis Host bridge callers. Methods are discovered by
 * `wails3 generate bindings`.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

/**
 * CurrentURL returns the URL currently scheduled for the main window.
 */
export function CurrentURL(): $CancellablePromise<string> {
    return $Call.ByID(152939581);
}

/**
 * HideWindow hides the main window (tray keeps the process alive).
 */
export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(1601551219);
}

/**
 * LoadHostURL navigates the main window to a Cordis Host / desktop UI origin
 * (typically http://127.0.0.1:<port>/ from desktopLoopbackBrowserUrl).
 */
export function LoadHostURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(2329620894, url);
}

/**
 * OpenDirectoryDialog opens a native directory picker and returns the path.
 */
export function OpenDirectoryDialog(): $CancellablePromise<string> {
    return $Call.ByID(338629742);
}

/**
 * Quit requests application shutdown.
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(3900019188);
}

/**
 * ShowControlUI reloads the embedded Wails control page (asset server "/").
 */
export function ShowControlUI(): $CancellablePromise<void> {
    return $Call.ByID(2225449553);
}

/**
 * ShowInfoDialog shows a native information dialog.
 */
export function ShowInfoDialog(title: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(1571402046, title, message);
}

/**
 * ShowWindow focuses the main window.
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(1276471090);
}

/**
 * Status returns a short diagnostic string for the control panel.
 */
export function Status(): $CancellablePromise<string> {
    return $Call.ByID(1144694253);
}
